### Register User
POST https://kurbansejahtera-api.up.railway.app/auth/register
Content-Type: application/json

{
  "nama": "sqoq",
  "username": "jaassaa",
  "password": "password123",
  "role": "pembeli",
  "alamat": "123 Main St",
  "nomorHp": "08123456789"
}

### Login User
POST https://kurbansejahtera-api.up.railway.app/auth/login
Content-Type: application/json

{
  "username": "jaassaa",
  "password": "password123"
}


### Register Admin
POST https://kurbansejahtera-api.up.railway.app/auth/register
Content-Type: application/json


{
  "nama": "Jsffw",
  "username": "abuysW",
  "password": "password123",
  "role": "penjual",
  "alamat": "123 Main St",
  "nomorHp": "08123456789"
}

### Login Admin
POST https://kurbansejahtera-api.up.railway.app/auth/login
Content-Type: application/json

{
  "username": "abuysW",
  "password": "password123"
}
