### Mengambil semua entri DataPenjualan
GET https://kurbansejahtera-api.up.railway.app/datapenjualan
Accept: application/json

### Mengambil DataPenjualan berdasarkan ID
GET https://kurbansejahtera-api.up.railway.app/datapenjualan/1
Accept: application/json

### Menghapus DataPenjualan berdasarkan ID
DELETE https://kurbansejahtera-api.up.railway.app/datapenjualan/1
Accept: application/json
