### Test: POST /hewan (Create new hewan)
POST https://kurbansejahtera-api.up.railway.app/hewan
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InBlbmp1YWwiLCJpYXQiOjE3MjE5OTk1ODIsImV4cCI6MTcyMjAwMzE4Mn0.qaA5vmZ4bS8W61i_VAGxcQqdzPHvkbxhh5WcLweYDaY

{
  "jenis": "Kambing",
  "umur": "2 tahun",
  "harga": 5000000
}

### Test: GET /hewan (Get all hewan)
GET https://kurbansejahtera-api.up.railway.app/hewan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InBlbmp1YWwiLCJpYXQiOjE3MjE5OTk1ODIsImV4cCI6MTcyMjAwMzE4Mn0.qaA5vmZ4bS8W61i_VAGxcQqdzPHvkbxhh5WcLweYDaY
### Test: GET /hewan/:id (Get hewan by ID)
GET https://kurbansejahtera-api.up.railway.app/hewan/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InBlbmp1YWwiLCJpYXQiOjE3MjE5OTk1ODIsImV4cCI6MTcyMjAwMzE4Mn0.qaA5vmZ4bS8W61i_VAGxcQqdzPHvkbxhh5WcLweYDaY

### Test: PUT /hewan/:id (Update hewan by ID)
PUT https://kurbansejahtera-api.up.railway.app/hewan/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InBlbmp1YWwiLCJpYXQiOjE3MjE5OTk1ODIsImV4cCI6MTcyMjAwMzE4Mn0.qaA5vmZ4bS8W61i_VAGxcQqdzPHvkbxhh5WcLweYDaY

{
  "jenis": "Kambing",
  "umur": 3,
  "harga": 3000000
}

### Test: DELETE /hewan/:id (Delete hewan by ID)
DELETE https://kurbansejahtera-api.up.railway.app/hewan/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InBlbmp1YWwiLCJpYXQiOjE3MjE5MDY2NDUsImV4cCI6MTcyMTkxMDI0NX0.JwR3BQdI0XFrOQIWXfpR4WGEDiLp36cVWbTgjAryhlA  