

### Menguji endpoint GET untuk mengambil semua entri pembeli
GET https://kurbansejahtera-api.up.railway.app/pembeli
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InBlbmp1YWwiLCJpYXQiOjE3MjIwMDA4ODgsImV4cCI6MTcyMjAwNDQ4OH0.kS0nbowEMnCzOetm0tvZ3FCbxyICL3r2RwIye7GeZrM


### Menguji endpoint GET untuk mengambil entri pembeli berdasarkan ID
GET https://kurbansejahtera-api.up.railway.app/pembeli/1


### Menguji endpoint DELETE untuk menghapus entri pembeli berdasarkan ID
DELETE https://kurbansejahtera-api.up.railway.app/pembeli/1
